# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

workflows:
  build:
    jobs:
      - build:
          context:
            - retrace-global-ci-ctx

jobs:
  build:
    machine: true
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          docker login --username $DOCKER_USER --password $DOCKER_PASSWORD

      # build the application image
      - run: docker build -t retrace/openssl:$CIRCLE_BRANCH .

      # deploy the image
      - run: docker run -it -v $(pwd):/opt/openssl retrace/openssl:$CIRCLE_BRANCH
      - run:
          name: Creating Artifact
          command: |
            mkdir /tmp/artifacts;
            cp libcrypto.* /tmp/artifacts/;
            cp libssl.* /tmp/artifacts/;
